---

- hosts: all
  remote_user: ec2-user
  become: true
  tasks:
  
  # prereq - install module from ansible-galaxy
  # `ansible-galaxy collection install redhatinsights.insights`
  - name: Remove RHEL system from insights
    redhatinsights.insights.insights_register:
      state: absent

  - name: Unregister RHEL
    redhat_subscription:
      state: absent
    

